spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart-agriculture?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    userName: root
    password: 11111
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
mqtt:
  url: tcp://127.0.0.1:61613
  clientId: TEST_CLIENT
  topic: service/#
  username: admin
  password: password


